name: cthru-calculator
channels: [conda-forge, nodefaults]
dependencies:
  - python=3.10
  - doit=0.33.*
  - pandas=1.5.*
  - openpyxl=3.*
  - pygraphviz=1.7
  - ipysankeywidget=0.5.*
  - jupyter-book=0.13.*
  - notebook=6.*
  - jupytext=1.14.*
  - pytest=6.2.*
  - pip=23.*
  - pip:
      - git+https://github.com/ricklupton/floweaver.git@38215850519d08cd791145cde3c1e8fa0cfe928b#egg=floweaver
      - sphinx_probs_rdf==0.1.7
      - https://github.com/ukfires/probs-runner/archive/e13f5510ff59236827900d3185f0bd32594f4554.zip
