# Book settings
title: C-THRU Calculator system
author: Rick Lupton
copyright: "2023"
# logo: logo.png

# html:
#   favicon: "favicon.png"

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
  myst_dmath_double_inline: true

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinx_probs_rdf
  config:
    probs_rdf_system_prefix: "http://c-thru.org/analyses/calculator/system/"
